apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "frontend.fullname" . }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Values.global.branch }}
    app.kubernetes.io/component: react
    app.kubernetes.io/managed-by: helm
spec:
  revisionHistoryLimit: 2
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "frontend.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "frontend.name" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/name: frontend
        app.kubernetes.io/instance: {{ .Values.global.branch }}
        app.kubernetes.io/component: react
        app.kubernetes.io/managed-by: helm
    spec:
      {{- if eq .Values.initContainer "true"}}
      initContainers:
        {{ if eq .Values.provisioningProd.isRequired "true"}}
        - name: provisioning-prod
          image: "{{ .Values.provisioningProd.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "start"]
          env:
          {{- range $key, $value := .Values.provisioningProd.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
        {{ if eq .Values.provisioningTest.isRequired "true"}}
        - name: provisioning-test
          image: "{{ .Values.provisioningTest.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["npm", "start"]
          env:
          {{- range $key, $value := .Values.provisioningTest.env }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.frontend.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          resources:
            requests:
              memory: {{ .Values.frontend.resources.memRequest }}
              cpu: {{ .Values.frontend.resources.cpuRequest }}
            limits:
              memory: {{ .Values.frontend.resources.memLimit }}
              cpu: {{ .Values.frontend.resources.cpuLimit }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.frontend.port }}
