{{- if or .Values.tags.blockchain .Values.tags.minimal}}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: read-services
  namespace: {{ .Values.global.namespace }}
subjects:
- kind: ServiceAccount
  name: blockchain-sa # Name is case sensitive
roleRef:
  kind: Role #this must be Role or ClusterRole
  name: service-reader # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
{{- end }}